name: Atualizar Sitemap

on:
  push:
    branches:
      - main
  schedule:
    - cron: "0 3 * * *"  # Executa todo dia às 03:00 UTC

jobs:
  update_sitemap:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do repositório
        uses: actions/checkout@v4

      - name: Configurar Git
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"

      - name: Gerar Sitemap.xml
        run: |
          echo '<?xml version="1.0" encoding="UTF-8"?>' > sitemap.xml
          echo '<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">' >> sitemap.xml
          for file in *.html; do
            echo "  <url><loc>https://AcertosOnline.github.io/Resultados/$file</loc></url>" >> sitemap.xml
          done
          echo '</urlset>' >> sitemap.xml

      - name: Commit e Push se houver mudanças
        run: |
          git add sitemap.xml
          git diff --staged --quiet || (git commit -m "Atualizando sitemap.xml automaticamente" && git push)
